// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _phonesendmsgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _captchaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _captcha0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _phoneloginMw() []app.HandlerFunc {
	// your code...
	return nil
}
